name: landsattrend
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - bottleneck
  - fiona
  - gdal=3.3.2
  - geopandas=0.9.0
  - googledrivedownloader=0.4
  - jupyter
  - notebook
  - pycaret
  - rasterio
  - scikit-image=0.19.1
  - scikit-learn=0.23
  - netCDF4
  - pip:
    - pyclowder
