name: landsattrend2-ray
channels:
  - conda-forge
  - defaults
dependencies:
  - bottleneck
  - python=3.8
  - fiona=1.8.20
  - gdal=3.3.2
  - geopandas=0.9.0
  - googledrivedownloader=0.4
  - jupyter
  - netcdf4
  - notebook
  - numpy=1.21
  - pycaret
  - rasterio=1.2
  - scikit-image=0.19.1
  - scikit-learn=0.23
  - scipy=1.7.1
  - earthengine-api
  - pip
  - pip:
    - getfilelistpy
    - ray[default]
