name: landsattrend2
channels:
  - conda-forge
  - defaults
dependencies:
  - affine=2.3.0
  - attrs=20.1.0
  - blas=1.0
  - boost-cpp=1.72.0
  - bottleneck=1.3.2
  - bzip2=1.0.8
  - ca-certificates=2020.6.20
  - certifi=2020.6.20
  - cfitsio=3.470
  - cftime=1.2.1
  - click=7.1.2
  - click-plugins=1.1.1
  - cligj=0.5.0
  - cloudpickle=1.6.0
  - curl=7.71.1
  - cycler=0.10.0
  - cytoolz=0.10.1
  - dask-core=2.25.0
  - decorator=4.4.2
  - expat=2.2.9
  - fiona=1.8.9.post2
  - freetype=2.10.2
  - freexl=1.0.5
  - gdal=2.4.4
  - geopandas=0.6.1
  - geos=3.8.1
  - geotiff=1.5.1
  - gettext=0.19.8.1
  - glib=2.65.0
  - hdf4=4.2.13
  - hdf5=1.10.5
  - icc_rt=2019.0.0
  - icu=64.2
  - imageio=2.9.0
  - intel-openmp=2019.4
  - joblib=0.16.0
  - jpeg=9d
  - kealib=1.4.13
  - kiwisolver=1.2.0
  - krb5=1.17.1
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcurl=7.71.1
  - libffi=3.2.1
  - libgdal=2.4.4
  - libiconv=1.16
  - libkml=1.3.0
  - liblapack=3.8.0
  - libnetcdf=4.7.4
  - libpng=1.6.37
  - libpq=12.3
  - libspatialindex=1.9.3
  - libspatialite=4.3.0a
  - libssh2=1.9.0
  - libtiff=4.1.0
  - libwebp-base=1.1.0
  - libxml2=2.9.10
  - lz4-c=1.9.2
  - m2w64-expat=2.1.1
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gettext=0.19.7
  - m2w64-gmp=6.1.0
  - m2w64-libiconv=1.14
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - m2w64-xz=5.2.2
  - matplotlib-base=3.3.1
  - mkl=2018.0.3
  - msys2-conda-epoch=20160418
  - munch=2.5.0
  - netcdf4=1.5.3
  - networkx=2.5
  - numpy=1.19.1
  - olefile=0.46
  - openjpeg=2.3.1
  - openssl=1.1.1g
  - pandas=0.23.4
  - pcre=8.44
  - pillow=7.2.0
  - pip=20.2.2
  - pixman=0.38.0
  - poppler=0.67.0
  - poppler-data=0.4.9
  - postgresql=12.3
  - proj=7.0.0
  - pyparsing=2.4.7
  - pyproj=2.6.1.post1
  - python=3.6.11
  - python-dateutil=2.8.1
  - python_abi=3.6
  - pytz=2020.1
  - pywavelets=1.1.1
  - pyyaml=5.3.1
  - rasterio=1.0.28
  - rtree=0.9.4
  - scikit-image=0.15.0
  - scikit-learn=0.19.1
  - scipy=1.1.0
  - setuptools=49.6.0
  - shapely=1.7.1
  - six=1.15.0
  - snuggs=1.4.7
  - sqlite=3.33.0
  - tbb=2020.1
  - tiledb=2.0.8
  - tk=8.6.10
  - toolz=0.10.0
  - tornado=6.0.4
  - vc=14.1
  - vs2015_runtime=14.16.27012
  - wheel=0.35.1
  - wincertstore=0.2
  - xerces-c=3.2.2
  - xz=5.2.5
  - yaml=0.2.5
  - zlib=1.2.11
  - zstd=1.4.5

