channels:
  - conda-forge
  - defaults
dependencies:
  - earthengine-api
  - fiona=1.8.20
  - gdal=3.3.2
  - geopandas=0.9.0
  - googledrivedownloader=0.4
  - joblib=1.0.1
  - jupyter
  - matplotlib=3.4.3
  - notebook
  - numpy=1.21
  - pandas=1.3
  - pycaret
  - python=3.8
  - rasterio=1.2
  - scikit-image=0.19.1
  - scikit-learn=0.23
  - scipy=1.7.1
  - seaborn=0.11.2
  - tqdm
  - pip:
    - getfilelistpy
