name: landsattrend2
channels:
  - conda-forge
dependencies:
  - python=3.6.11
  - Bottleneck=1.3.2
  - GDAL=2.4.3
  - pandas=0.23.0
  - geopandas=0.6.1
  - scikit-learn=0.21.3
  - scikit-image=0.15.0
  - rasterio=1.0.28
  - joblib=0.14.0
  - fiona
  - netCDF4=1.5.3